return {
  id      = "nvidia",
  name    = "NVIDIA NIM",
  baseUrl = "https://integrate.api.nvidia.com/v1",
  api     = "openai-completions",
  needs_key = true,
  key_hint  = "nvapi-...",
  docs    = "https://build.nvidia.com",
  models  = {
    {
      id            = "nvidia/nemotron-3-super-120b-a12b",
      name          = "Nemotron 3 Super 120B",
      reasoning     = true,
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 262144,
      maxTokens     = 8192,
    },
    {
      id            = "moonshotai/kimi-k2.5",
      name          = "Kimi K2.5 (NVIDIA)",
      reasoning     = true,
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 262144,
      maxTokens     = 8192,
    },
    {
      id            = "minimaxai/minimax-m2.5",
      name          = "Minimax M2.5 (NVIDIA)",
      reasoning     = true,
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 196608,
      maxTokens     = 8192,
    },
    {
      id            = "z-ai/glm5",
      name          = "GLM 5 (NVIDIA)",
      reasoning     = true,
      reasoning_style = "chat_template_kwargs",
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 202752,
      maxTokens     = 8192,
    },
    {
      id            = "z-ai/glm-5.1",
      name          = "GLM 5.1 (NVIDIA)",
      reasoning     = true,
      reasoning_style = "chat_template_kwargs",
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 202752,
      maxTokens     = 131072,
    },
  },
}
