return {
  id      = "openrouter",
  name    = "OpenRouter",
  baseUrl = "https://openrouter.ai/api/v1",
  api     = "openai-completions",
  needs_key = true,
  key_hint  = "sk-or-...",
  docs    = "https://openrouter.ai/keys",
  models  = {
    {
      id            = "google/gemma-4-31b-it:free",
      name          = "Gemma 4 31B (Free)",
      reasoning     = true,
      default_effort = "high",
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 262144,
      maxTokens     = 4096,
    },
    {
      id            = "google/gemma-3-27b-it:free",
      name          = "Gemma 3 27B (Free)",
      reasoning     = false,
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 131072,
      maxTokens     = 4096,
    },
    {
      id            = "meta-llama/llama-4-maverick:free",
      name          = "Llama 4 Maverick (Free)",
      reasoning     = false,
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 131072,
      maxTokens     = 4096,
    },
    {
      id            = "deepseek/deepseek-r1:free",
      name          = "DeepSeek R1 (Free)",
      reasoning     = true,
      default_effort = "high",
      input         = {"text"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 163840,
      maxTokens     = 8192,
    },
    {
      id            = "openrouter/auto",
      name          = "OpenRouter Auto",
      reasoning     = false,
      input         = {"text", "image"},
      cost          = {input=0, output=0, cacheRead=0, cacheWrite=0},
      contextWindow = 200000,
      maxTokens     = 8192,
    },
  },
}